### ISSUE TITLE
Name aws-encryption

### ISSUE THREAD

**Issue by adamchainz** [awslabs/aws-encryption-sdk-python#1]
I'm now the owner of the name aws-encryption, trying to install it currently fails with a message "Did you mean to install aws-encryption-sdk?" ([code](https://github.com/adamchainz/aws-encryption/blob/master/setup.py)).

Maybe you want it though?

**Comment by mattsb42-aws** [comment]
Thanks, Adam.  We don't currently have any plans for something by that name, but the avoidance of a future name grab is appreciated.  Would you mind adding the user "aws-crypto-builder-tools" as an owner on the pypi package?  I'll discuss with the team and determine what we want to do with it.

**Comment by adamchainz** [comment]
Done
