### ISSUE TITLE
encryption_context isn't respected on decrypt

### ISSUE THREAD

**Issue by troylar** [awslabs/aws-encryption-sdk-python#4]

**Comment by mattsb42-aws** [comment]
On the decrypt path, the encryption context is read from the [message header](http://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/message-format.html#header-aad) and passed to the master key(s) when using them to decrypt the data key.  You are correct that the top-level decrypt methods do not accept the encryption context as input, and as such the encryption context is not checked _outside_ of the master key(s).

We do recommend that developers check the encryption context after decrypting to ensure that it matches expected values, [as shown in our examples](http://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/python-example-code.html), but this type of validation check is not currently incorporated into the client itself.
