### ISSUE TITLE
Cache KMS plaintext and encrypted datakeys with some TTL?

### ISSUE THREAD

**Issue by gregsterin** [awslabs/aws-encryption-sdk-python#5]
Hi,

I've noticed that each call to encrypt() in the SDK results in network calls to KMS for GenerateDataKey and Encrypt. In my use case, I am using Kinesis and I would like encrypt each record in Kinesis using aws-encryption-sdk-python. Since I can have many records I need to encrypt per second, it would be nice if the SDK would cache data keys for some TTL, so that I'm not making network calls for each record I need to encrypt, as there can be hundreds-thousands of these per second. Current measurements suggest that each call to encrypt takes ~50ms, the majority of this time due to the network calls.

Is there a recommended way to handle such use case?

If not, I would suggest adding two optional kwargs to the KMS key provider:

* cache_kms_client_response
* kms_client_response_cache_ttl,

such that I can create a key provider that caches the keys for some time to fix this problem.

**Comment by mattsb42-aws** [comment]
Yes, currently each operation requires a call to each master key used.  Please see this forum thread[1] for more information on data key caching, and please feel free to reach out to me there for more information about how it might help your use case.

[1] https://forums.aws.amazon.com/thread.jspa?threadID=257153

**Comment by mattsb42-aws** [comment]
Data key caching has been added in the 1.3.0 release.  Please see this blog post for more information:
https://aws.amazon.com/blogs/security/aws-encryption-sdk-how-to-decide-if-data-key-caching-is-right-for-your-application/
