### ISSUE TITLE
DefaultCryptoMaterialsManager docstring incorrectly indicates that algorithm is a configurable parameter

### ISSUE THREAD

**Issue by mattsb42** [awslabs/aws-encryption-sdk-python#8]
`DefaultCrytoMaterialsManager` docstring incorrectly indicates that algorithm is configurable.  Behavior is as intended, but I missed clearing out this docstring.

https://github.com/awslabs/aws-encryption-sdk-python/blob/b6a2bbca4db6ab46d65fe7e2eacfffe25abff3a2/aws_encryption_sdk/materials_managers/default.py#L26

**Comment by mattsb42-aws** [comment]
This is addressed in #12
